server:
  port: 8084
spring:
  application:
    name: tensquare-eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url: #客户端与EurekaServer交互的地址，如果是集群，也需要写其 它Server的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false # ⾃⼰就是服务不需要注册⾃⼰
    fetch-registry: false #⾃⼰就是服务不需要从Eureka Server获取服务信息,默认为true，置为false